version: '3'

services:
  db:
    image: postgres:13
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: duotest-password
      POSTGRES_USER: duotest
      POSTGRES_DB: testdb

  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -b '0.0.0.0'"
    volumes:
      - .:/myapp
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://duotest:duotest-password@db:5432/testdb
      RAILS_ENV: development

volumes:
  db-data:
    driver: local